https://ic.unicamp.br/~lehilton/mc102qr/index.html
  https://ic.unicamp.br/~lehilton/mc102qr/apresentacao.html
  https://ic.unicamp.br/~lehilton/mc102qr/fixacao.html
    https://ic.unicamp.br/~lehilton/mc102qr/fixacao/00-algoritmo.html
      https://ic.unicamp.br/~lehilton/mc102qr/fixacao/01-variaveis.html
        https://ic.unicamp.br/~lehilton/mc102qr/fixacao/02-condicional.html
          https://ic.unicamp.br/~lehilton/mc102qr/fixacao/03-repeticao.html
            https://ic.unicamp.br/~lehilton/mc102qr/fixacao/04-funcoes.html
              https://ic.unicamp.br/~lehilton/mc102qr/fixacao/05-praticas.html
                https://ic.unicamp.br/~lehilton/mc102qr/fixacao/06-listas.html
                  https://ic.unicamp.br/~lehilton/mc102qr/fixacao/07-ordenacao.html
                    https://ic.unicamp.br/~lehilton/mc102qr/fixacao/08-matrizes.html
                      https://ic.unicamp.br/~lehilton/mc102qr/fixacao/09-arquivos.html
                        https://ic.unicamp.br/~lehilton/mc102qr/fixacao/10-colecoes.html
                          https://ic.unicamp.br/~lehilton/mc102qr/fixacao/11-eficiencia.html
                            https://ic.unicamp.br/~lehilton/mc102qr/fixacao/12-recursao.html
  https://ic.unicamp.br/~lehilton/mc102qr/unidades/01-problemas-algoritmos.html
    https://ic.unicamp.br/~lehilton/mc102qr/unidades/02-escrevendo-algoritmos.html
      https://ic.unicamp.br/~lehilton/mc102qr/unidades/03-linguagens-programacao.html
        https://ic.unicamp.br/~lehilton/mc102qr/unidades/04-estruturas-elementares.html
          https://ic.unicamp.br/~lehilton/mc102qr/unidades/05-listas.html
            https://ic.unicamp.br/~lehilton/mc102qr/unidades/06-funcoes.html
              https://ic.unicamp.br/~lehilton/mc102qr/unidades/07-algortimos-iterativos.html
                https://ic.unicamp.br/~lehilton/mc102qr/unidades/08-matrizes.html
                  https://ic.unicamp.br/~lehilton/mc102qr/unidades/09-colecoes.html
                    https://ic.unicamp.br/~lehilton/mc102qr/unidades/10-eficiencia.html
                      https://ic.unicamp.br/~lehilton/mc102qr/unidades/11-recursao.html
                        https://ic.unicamp.br/~lehilton/mc102qr/tarefas/14-recursao.html
                          https://ic.unicamp.br/~lehilton/mc102qr/tarefas/13-algoritmos-eficientes.html
                            https://ic.unicamp.br/~lehilton/mc102qr/tarefas/12-colecoes-dinamicas.html
                              https://ic.unicamp.br/~lehilton/mc102qr/tarefas/11-dicionarios-e-tuplas.html
                                https://ic.unicamp.br/~lehilton/mc102qr/tarefas/10-imagens-binarias.html
                                  https://ic.unicamp.br/~lehilton/mc102qr/tarefas/09-conceito-frequencia.html
                                    https://ic.unicamp.br/~lehilton/mc102qr/tarefas/08-funcoes.html
                                      https://ic.unicamp.br/~lehilton/mc102qr/tarefas/07-percorrer-listas.html
                                        https://ic.unicamp.br/~lehilton/mc102qr/tarefas/06-listas.html
                                          https://ic.unicamp.br/~lehilton/mc102qr/tarefas/05-condicional.html
                                            https://ic.unicamp.br/~lehilton/mc102qr/tarefas/04-entendendo-algoritmos.html
                                              https://ic.unicamp.br/~lehilton/mc102qr/tarefas/03-estruturas-controle.html
                                                https://ic.unicamp.br/~lehilton/mc102qr/tarefas/02-problemas-algoritmos.html
                                                  https://ic.unicamp.br/~lehilton/mc102qr/tarefas/01-primeira-tarefa.html
